/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_api_v1_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products */
        get: operations["products_api_v1_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** By Slug */
        get: operations["by_slug_api_v1_products_by_slug__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** By Id */
        get: operations["by_id_api_v1_products__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Collections */
        get: operations["collections_api_v1_collections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Collection */
        get: operations["collection_api_v1_collections__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guest Sessions */
        post: operations["guest_sessions_api_v1_guest_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guest Session */
        get: operations["guest_session_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cart */
        get: operations["get_cart_api_v1_cart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Quantity */
        put: operations["set_quantity_api_v1_cart_items__product_id__put"];
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_v1_cart_items__product_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Quote */
        post: operations["create_quote_api_v1_draft_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkout-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Draft */
        post: operations["save_draft_api_v1_checkout_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkout-drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_v1_checkout_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_admin_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Session */
        get: operations["admin_session_api_v1_admin_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_admin_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_v1_admin_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_v1_admin_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_admin_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_api_v1_admin_products__product_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bundle */
        get: operations["get_bundle_api_v1_admin_products__product_id__bundle_get"];
        /** Replace Bundle */
        put: operations["replace_bundle_api_v1_admin_products__product_id__bundle_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}/site-price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Site Price */
        put: operations["set_site_price_api_v1_admin_products__product_id__site_price_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/checkout-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drafts */
        get: operations["list_drafts_api_v1_admin_checkout_drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/checkout-drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_v1_admin_checkout_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Media */
        post: operations["create_media_api_v1_admin_products__product_id__media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Media */
        delete: operations["delete_media_api_v1_admin_products__product_id__media__media_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressDemo */
        AddressDemo: {
            /** City */
            city: string;
            /** Address Line */
            address_line: string;
            /** Postal Code */
            postal_code?: string | null;
        };
        /** AdminDraftDTO */
        AdminDraftDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * State
             * @constant
             */
            state: "saved";
            /**
             * Channel
             * @constant
             */
            channel: "site";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            goods_total: components["schemas"]["Money"];
            /** Contact */
            contact: {
                [key: string]: unknown;
            };
            /** Address */
            address: {
                [key: string]: unknown;
            };
        };
        /** AdminLoginDTO */
        AdminLoginDTO: {
            /** Email */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** AdminSessionDTO */
        AdminSessionDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Permissions */
            permissions: string[];
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** Availability */
        Availability: {
            /**
             * State
             * @default unknown
             * @constant
             */
            state: "unknown";
            /** Quantity */
            quantity?: null;
            /** Source */
            source?: null;
            /** Observed At */
            observed_at?: null;
        };
        /** BundleAdminComponentDTO */
        BundleAdminComponentDTO: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Sku */
            sku: string;
            /** Title */
            title: string;
            /** Quantity */
            quantity: number;
            base_unit_price: components["schemas"]["Money"];
        };
        /** BundleAdminDTO */
        BundleAdminDTO: {
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Version */
            version: number;
            /** Components */
            components: components["schemas"]["BundleAdminComponentDTO"][];
        };
        /** BundleComponentDTO */
        BundleComponentDTO: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Sku */
            sku: string;
            /** Title */
            title: string;
            /** Quantity */
            quantity: number;
            base_unit_price: components["schemas"]["Money"];
        };
        /** BundleComponentInput */
        BundleComponentInput: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Quantity */
            quantity: number;
        };
        /** BundleDTO */
        BundleDTO: {
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Version */
            version: number;
            /** Components */
            components: components["schemas"]["BundleComponentDTO"][];
        };
        /** BundleWriteDTO */
        BundleWriteDTO: {
            /** Components */
            components: components["schemas"]["BundleComponentInput"][];
        };
        /** CapabilitiesDTO */
        CapabilitiesDTO: {
            /**
             * Mode
             * @default foundation_demo
             * @constant
             */
            mode: "foundation_demo";
            /**
             * Real Checkout
             * @default false
             * @constant
             */
            real_checkout: false;
            /**
             * Payment
             * @default false
             * @constant
             */
            payment: false;
            /**
             * Delivery
             * @default false
             * @constant
             */
            delivery: false;
            /**
             * Stock Reservation
             * @default false
             * @constant
             */
            stock_reservation: false;
            /**
             * Sms
             * @default false
             * @constant
             */
            sms: false;
            /**
             * Customer Account
             * @default false
             * @constant
             */
            customer_account: false;
            /**
             * Returns
             * @default false
             * @constant
             */
            returns: false;
            /**
             * Refunds
             * @default false
             * @constant
             */
            refunds: false;
            /**
             * Reviews
             * @default false
             * @constant
             */
            reviews: false;
        };
        /** CartDTO */
        CartDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
            /** Items */
            items: components["schemas"]["CartLine"][];
            goods_total: components["schemas"]["Money"] | null;
            /** Can Quote */
            can_quote: boolean;
            delivery?: components["schemas"]["CartDelivery"];
            /** Payable Total */
            payable_total?: null;
        };
        /** CartDelivery */
        CartDelivery: {
            /**
             * State
             * @default not_connected
             * @constant
             */
            state: "not_connected";
            /** Amount */
            amount?: null;
        };
        /** CartLine */
        CartLine: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Quantity */
            quantity: number;
            unit_price: components["schemas"]["Money"] | null;
            line_total: components["schemas"]["Money"] | null;
            /** Issue */
            issue: ("PRODUCT_INACTIVE" | "PRICE_MISSING" | "BUNDLE_INVALID" | "CALCULATION_OVERFLOW") | null;
        };
        /** CatalogDelivery */
        CatalogDelivery: {
            /**
             * State
             * @default not_connected
             * @constant
             */
            state: "not_connected";
        };
        /** CategoryDTO */
        CategoryDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /** CategoryPage */
        CategoryPage: {
            /** Items */
            items: components["schemas"]["CategoryDTO"][];
        };
        /** CollectionDTO */
        CollectionDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /** CollectionDetail */
        CollectionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Items */
            items: components["schemas"]["ProductSummary"][];
        };
        /** CollectionPage */
        CollectionPage: {
            /** Items */
            items: components["schemas"]["CollectionDTO"][];
        };
        /** ContactDemo */
        ContactDemo: {
            /** Phone */
            phone: string;
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
        };
        /** DraftCapabilities */
        DraftCapabilities: {
            /**
             * Pay
             * @default false
             * @constant
             */
            pay: false;
            /**
             * Cancel
             * @default false
             * @constant
             */
            cancel: false;
            /**
             * Return
             * @default false
             * @constant
             */
            return: false;
            /**
             * Submit Delivery
             * @default false
             * @constant
             */
            submit_delivery: false;
        };
        /** DraftComponentSnapshot */
        DraftComponentSnapshot: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Sku */
            sku: string;
            /** Title */
            title: string;
            /** Quantity Per Bundle */
            quantity_per_bundle: number;
            /** Total Quantity */
            total_quantity: number;
            base_unit_price: components["schemas"]["Money"];
        };
        /** DraftDTO */
        DraftDTO: {
            /** Items */
            items: components["schemas"]["DraftLineSnapshot"][];
            goods_total: components["schemas"]["Money"];
            delivery?: components["schemas"]["CartDelivery"];
            /** Payable Total */
            payable_total?: null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * State
             * @default saved
             * @constant
             */
            state: "saved";
            /**
             * Channel
             * @default site
             * @constant
             */
            channel: "site";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            contact: components["schemas"]["ContactDemo"];
            address: components["schemas"]["AddressDemo"];
            capabilities?: components["schemas"]["DraftCapabilities"];
            /**
             * Message
             * @default Заявка сохранена; оплата и доставка пока не подключены
             * @constant
             */
            message: "Заявка сохранена; оплата и доставка пока не подключены";
        };
        /** DraftLineSnapshot */
        DraftLineSnapshot: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Sku */
            sku: string;
            /** Title */
            title: string;
            /** Quantity */
            quantity: number;
            unit_price: components["schemas"]["Money"];
            line_total: components["schemas"]["Money"];
            /** Bundle Version Id */
            bundle_version_id?: string | null;
            /** Components */
            components?: components["schemas"]["DraftComponentSnapshot"][];
        };
        /** DraftPageDTO */
        DraftPageDTO: {
            /** Items */
            items: components["schemas"]["AdminDraftDTO"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** DraftQuoteDTO */
        DraftQuoteDTO: {
            /** Items */
            items: components["schemas"]["DraftLineSnapshot"][];
            goods_total: components["schemas"]["Money"];
            delivery?: components["schemas"]["CartDelivery"];
            /** Payable Total */
            payable_total?: null;
            /**
             * Quote Id
             * Format: uuid
             */
            quote_id: string;
            /** Cart Version */
            cart_version: number;
            /**
             * State
             * @default valid
             * @constant
             */
            state: "valid";
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            capabilities?: components["schemas"]["QuoteCapabilities"];
        };
        /** DraftSaveCommand */
        DraftSaveCommand: {
            /**
             * Quote Id
             * Format: uuid
             */
            quote_id: string;
            contact: components["schemas"]["ContactDemo"];
            address: components["schemas"]["AddressDemo"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MediaDTO */
        MediaDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "image" | "video";
            /** Url */
            url: string;
            /** Alt Text */
            alt_text: string;
            /** Position */
            position: number;
        };
        /** Money */
        Money: {
            /** Amount Minor */
            amount_minor: string;
            /**
             * Currency
             * @default RUB
             * @constant
             */
            currency: "RUB";
        };
        /** ProductAdminDTO */
        ProductAdminDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sku */
            sku: string;
            /** Slug */
            slug: string;
            /**
             * Type
             * @enum {string}
             */
            type: "single" | "bundle";
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Active */
            active: boolean;
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Seo */
            seo: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
            price?: components["schemas"]["Money"] | null;
            original_price?: components["schemas"]["Money"] | null;
            /** Related Product Ids */
            related_product_ids?: string[];
            /** Media */
            media?: components["schemas"]["MediaDTO"][];
            bundle?: components["schemas"]["BundleAdminDTO"] | null;
        };
        /** ProductAdminPageDTO */
        ProductAdminPageDTO: {
            /** Items */
            items: components["schemas"]["ProductAdminDTO"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ProductCreateDTO
         * @description The one command that can assign a SKU.
         *
         *     SKU is deliberately absent from ProductWriteDTO: once a row exists it is
         *     an immutable catalog identity and cannot be changed through PATCH.
         */
        ProductCreateDTO: {
            /** Sku */
            sku: string;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Type
             * @default single
             * @enum {string}
             */
            type: "single" | "bundle";
            /** Slug */
            slug?: string | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            } | null;
            /** Seo */
            seo?: {
                [key: string]: unknown;
            } | null;
            /** Related Product Ids */
            related_product_ids?: string[];
            /** Category Ids */
            category_ids?: string[];
            price: components["schemas"]["Money"];
            original_price?: components["schemas"]["Money"] | null;
        };
        /** ProductDetail */
        ProductDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sku */
            sku: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "single" | "bundle";
            price: components["schemas"]["Money"];
            original_price?: components["schemas"]["Money"] | null;
            thumbnail?: components["schemas"]["MediaDTO"] | null;
            availability?: components["schemas"]["Availability"];
            /** Version */
            version: number;
            /** Description */
            description: string;
            /** Categories */
            categories: components["schemas"]["CategoryDTO"][];
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Seo */
            seo: {
                [key: string]: unknown;
            };
            /** Media */
            media: components["schemas"]["MediaDTO"][];
            /** Related Product Ids */
            related_product_ids: string[];
            bundle?: components["schemas"]["BundleDTO"] | null;
            delivery?: components["schemas"]["CatalogDelivery"];
        };
        /** ProductPage */
        ProductPage: {
            /** Items */
            items: components["schemas"]["ProductSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ProductSummary */
        ProductSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sku */
            sku: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "single" | "bundle";
            price: components["schemas"]["Money"];
            original_price?: components["schemas"]["Money"] | null;
            thumbnail?: components["schemas"]["MediaDTO"] | null;
            availability?: components["schemas"]["Availability"];
            /** Version */
            version: number;
        };
        /** ProductWriteDTO */
        ProductWriteDTO: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Active */
            active?: boolean | null;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            } | null;
            /** Seo */
            seo?: {
                [key: string]: unknown;
            } | null;
            /** Related Product Ids */
            related_product_ids?: string[] | null;
        };
        /** QuantityCommand */
        QuantityCommand: {
            /** Quantity */
            quantity: number;
        };
        /** QuoteCapabilities */
        QuoteCapabilities: {
            /**
             * Save Draft
             * @default true
             * @constant
             */
            save_draft: true;
            /**
             * Pay
             * @default false
             * @constant
             */
            pay: false;
            /**
             * Submit Delivery
             * @default false
             * @constant
             */
            submit_delivery: false;
        };
        /** QuoteCommand */
        QuoteCommand: {
            /** Cart Version */
            cart_version: number;
        };
        /** SessionDTO */
        SessionDTO: {
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** SitePriceWriteDTO */
        SitePriceWriteDTO: {
            price: components["schemas"]["Money"];
            original_price?: components["schemas"]["Money"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryPage"];
                };
            };
        };
    };
    products_api_v1_products_get: {
        parameters: {
            query?: {
                q?: string;
                category?: string | null;
                sort?: "title_asc" | "price_asc" | "price_desc";
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    by_slug_api_v1_products_by_slug__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    by_id_api_v1_products__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collections_api_v1_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPage"];
                };
            };
        };
    };
    collection_api_v1_collections__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guest_sessions_api_v1_guest_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Origin rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guest_session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
        };
    };
    get_cart_api_v1_cart_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartDTO"];
                };
            };
        };
    };
    set_quantity_api_v1_cart_items__product_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuantityCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartDTO"];
                };
            };
            /** @description Version conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description If-Match required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_item_api_v1_cart_items__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartDTO"];
                };
            };
            /** @description Version conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description If-Match required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_quote_api_v1_draft_quotes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftQuoteDTO"];
                };
            };
            /** @description Cart changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_draft_api_v1_checkout_drafts_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftSaveCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDTO"];
                };
            };
            /** @description Idempotency, cart or quote conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Quote expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Idempotency-Key required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_draft_api_v1_checkout_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDTO"];
                };
            };
            /** @description Unknown or foreign draft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_admin_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionDTO"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_session_api_v1_admin_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionDTO"];
                };
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_api_v1_admin_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF or Origin rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_products_api_v1_admin_products_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminPageDTO"];
                };
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_v1_admin_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminDTO"];
                };
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission or CSRF rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description SKU or slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_admin_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminDTO"];
                };
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown product */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_admin_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductWriteDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminDTO"];
                };
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission or CSRF rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stale product version */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bundle_api_v1_admin_products__product_id__bundle_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleAdminDTO"];
                };
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown bundle */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_bundle_api_v1_admin_products__product_id__bundle_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BundleWriteDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleAdminDTO"];
                };
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission or CSRF rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stale product version */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_site_price_api_v1_admin_products__product_id__site_price_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SitePriceWriteDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminDTO"];
                };
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission or CSRF rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stale product version */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drafts_api_v1_admin_checkout_drafts_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                created_from?: string | null;
                created_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftPageDTO"];
                };
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_v1_admin_checkout_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDraftDTO"];
                };
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown draft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_media_api_v1_admin_products__product_id__media_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    alt_text?: string;
                    position?: number;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDTO"];
                };
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission or CSRF rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stale product version or CAPABILITY_DISABLED decoder gate */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_media_api_v1_admin_products__product_id__media__media_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                product_id: string;
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission or CSRF rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stale product version */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description PostgreSQL unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesDTO"];
                };
            };
        };
    };
}
